#!/usr/bin/env bash

fact=1
i=2
if (( $# < 1 ))
then
  echo "usage : $0 <entier>"
  exit 1
fi

if (( $1 < 2 ))
then
  echo "n! = $fact"
else
  while (( $i <= $1 ))
  do
    fact=$(($fact * $i))
    i=$(($i + 1))
  done
  echo "n! = $fact"
fi
